"""
Pydantic models for the CtxCommerce API request and response structures.
"""
import json
from typing import Optional, Any, Union, Dict, List
from pydantic import BaseModel, Field, field_validator

class ChatRequest(BaseModel):
    """
    Represents an incoming chat message request from the client.
    """
    user_message: str = Field(..., max_length=500, description="The message sent by the user.")
    dom_context: Optional[Union[Dict[str, Any], str]] = Field(
        None, description="The current DOM context of the shop website (e.g., product ID, page title)."
    )

    @field_validator('dom_context')
    @classmethod
    def limit_context_size(cls, v):
        """Reject oversized DOM contexts to prevent payload flooding and token cost escalation."""
        if v is None:
            return v
        serialized = v if isinstance(v, str) else json.dumps(v)
        if len(serialized) > 15000:
            raise ValueError("DOM context payload exceeds the 15,000 character safety limit.")
        return v

class ChatResponse(BaseModel):
    """
    Represents the agent's reply to the chat message.
    """
    agent_reply: str = Field(..., description="The response generated by the AI sales agent.")
    action_target_id: Optional[str] = Field(None, description="The data-agent-id of the element the agent wants to click.")
    redirect_url: Optional[str] = Field(None, description="Relative URL to redirect the user to a product page.")
