"""
Pydantic models for the CtxCommerce API request and response structures.
"""
from typing import Optional, Any, Union, Dict
from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    """
    Represents an incoming chat message request from the client.
    """
    user_message: str = Field(..., description="The message sent by the user.")
    dom_context: Optional[Union[Dict[str, Any], str]] = Field(
        None, description="The current DOM context of the shop website (e.g., product ID, page title)."
    )

class ChatResponse(BaseModel):
    """
    Represents the agent's reply to the chat message.
    """
    agent_reply: str = Field(..., description="The response generated by the AI sales agent.")
    action_target_id: Optional[str] = Field(None, description="The data-agent-id of the element the agent wants to click.")
    redirect_url: Optional[str] = Field(None, description="Relative URL to redirect the user to a product page.")
